# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fondo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
    ]
